# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 50
    # Disable rebasing for pull requests, as having several open pull requests all get simultaneously rebased gets
    # noisy from a notification standpoint
    rebase-strategy: 'disabled'
    ignore:
      - dependency-name: 'react'
        versions: ['>=18']
      - dependency-name: 'react-dom'
        versions: ['>=18']
      # Docusaurus does not support v2 of mdx at the time of this writing.
      # See: https://github.com/facebook/docusaurus/issues/4029
      - dependency-name: '@mdx-js/react'
        versions: ['>=2']
